# Generated by Django 3.0 on 2020-09-08 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('cuit', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='00', max_length=20)),
                ('nombreConsultorio', models.CharField(blank=True, max_length=10, verbose_name='Nombre del consultorio')),
                ('domicilio', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('domicilio', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('especialidad', models.TextField(max_length=20)),
                ('consultorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='cuit+', to='users.Consultorio')),
            ],
        ),
    ]
