# Generated by Django 3.0 on 2020-09-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario', models.CharField(default='MEDICO', max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(default='MARIA', max_length=10)),
                ('apellido', models.CharField(default='GONZALEZ', max_length=10)),
                ('domicilio', models.CharField(default='JOSE HERNANDEZ 25', max_length=15)),
                ('mail', models.EmailField(default='MARIA@GMAILC.COM', max_length=254, null=True)),
                ('telefono', models.CharField(default='3624227225', max_length=15)),
                ('password', models.CharField(default='MEDICO', max_length=15)),
            ],
        ),
    ]
