# Generated by Django 3.0 on 2020-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200924_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnosmedico',
            name='fecha',
            field=models.DateField(blank=True, help_text='00/00/0000', null=True),
        ),
        migrations.AlterField(
            model_name='turnosmedico',
            name='hora',
            field=models.TimeField(blank=True, help_text='00:00', null=True),
        ),
    ]
