# Generated by Django 3.0 on 2020-09-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
