# Generated by Django 3.0 on 2020-09-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200908_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('hora', models.DateField()),
                ('fecha', models.TimeField()),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=10, null=True)),
                ('apellido', models.CharField(max_length=10, null=True)),
                ('domicilio', models.CharField(max_length=15, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hora',
        ),
    ]
