# Generated by Django 3.0 on 2020-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200909_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='nombres_y_apellido',
            field=models.CharField(default='MARIA GOMEZ', max_length=10),
        ),
    ]
