# Generated by Django 3.0 on 2020-09-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200909_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='medico',
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicos',
            field=models.CharField(choices=[('MARIA GOMEZ', 'Dra. MARIA GOMEZ')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombres_y_apellido',
            field=models.CharField(default='MARIA GOMEZ', max_length=30),
        ),
    ]
