# Generated by Django 3.0 on 2020-09-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200909_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaTurnosMedico1',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=10, null=True)),
                ('apellido', models.CharField(max_length=10, null=True)),
                ('domicilio', models.CharField(max_length=15, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaTurnosMedico2',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=10, null=True)),
                ('apellido', models.CharField(max_length=10, null=True)),
                ('domicilio', models.CharField(max_length=15, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medicos',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
