# Generated by Django 3.0 on 2020-09-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200909_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaturnosmedico1',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listaturnosmedico1',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listaturnosmedico2',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='listaturnosmedico2',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
