# Generated by Django 3.1.1 on 2020-09-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='domicilio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombres_y_apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
