# Generated by Django 3.1.1 on 2020-09-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200921_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnosMedico',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=10, null=True)),
                ('apellido', models.CharField(max_length=10, null=True)),
                ('domicilio', models.CharField(max_length=15, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.medico')),
            ],
        ),
    ]
