# Generated by Django 3.1.1 on 2020-09-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200922_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnosmedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='users.medico'),
        ),
    ]
