# Generated by Django 3.0 on 2020-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnosmedico',
            name='fecha',
            field=models.DateField(blank=True, help_text='Formato: 00/00/0000', null=True),
        ),
        migrations.AlterField(
            model_name='turnosmedico',
            name='hora',
            field=models.TimeField(blank=True, help_text='Formato: 00:00', null=True),
        ),
    ]
