# Generated by Django 3.0 on 2020-09-04 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200904_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('especialidad', models.TextField()),
                ('consultorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='cuit+', to='usuarios.Consultorio')),
            ],
        ),
    ]
