# Generated by Django 3.0 on 2020-09-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultorio',
            name='nombresDelConsultorio',
        ),
        migrations.AddField(
            model_name='consultorio',
            name='contraseña',
            field=models.CharField(default='00', max_length=20),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='nombreConsultorio',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
